version: '3'
services:
  app:
    container_name: goblogs
    tty: true
    build: .
    ports:
      - "8080:8080"
    expose:
      - "5432"
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgres 
    networks:
      - learning
  
  postgres:
    image: postgres:16-alpine
    container_name: postgres 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=goblogs
      - PGDATA=/var/lib/postgresql/data/pgdata

    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - learning
volumes:
  db-data:
      driver: "local"

# Networks to be created to facilitate communication between containers
networks:
  learning:
    driver: bridge